spring.application.name=SpringSecurityJWT
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.jpa.hibernate.ddl-auto=create
server.servlet.context-path=/api

# Sicurezza
security.jwt.secret-key=${JWT_KEY}